package com.feluu.pylife;

import android.os.Bundle;
import android.view.View;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.feluu.pylife.adapters.CarsAdapter;
import com.feluu.pylife.adapters.WheelsAdapter;
import com.feluu.pylife.models.ListModel;
import com.feluu.pylife.utils.SharedPref;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

public class CarsListActivity extends AppCompatActivity {

    private RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SharedPref sharedPref = new SharedPref(this);
        if (sharedPref.loadNightModeState()) {
            setTheme(R.style.AppThemeDark);
        } else {
            setTheme(R.style.AppTheme);
        }
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list_search);
        ImageView leaveActivity;
        ImageView bgMain;
        TextView activityTitle;

        leaveActivity = findViewById(R.id.exitActivity);
        bgMain = findViewById(R.id.bgmain);
        activityTitle = findViewById(R.id.top_title);
        recyclerView = findViewById(R.id.recyclerView);
        activityTitle.setText(R.string.cars_list_activity);

        leaveActivity.setOnClickListener((View v) -> finish());

        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));

        if (sharedPref.loadNightModeState()) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            getWindow().setStatusBarColor(getResources().getColor(R.color.statusColor));
            bgMain.setImageResource(R.drawable.bg_dark);
        }

        addCarsToRecycler();
    }

    private void addCarsToRecycler() {
        List<ListModel> carsList;

        carsList = new ArrayList<>();
        carsList.add(new ListModel(intToString(R.string.admiral_name), intToString(R.string.admiral_vmax), intToString(R.string.admiral_vmaxfmk), intToString(R.string.admiral_tax), intToString(R.string.admiral_reset), intToString(R.string.admiral_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/admiral.png"));
        carsList.add(new ListModel(intToString(R.string.alpha_name), intToString(R.string.alpha_vmax), intToString(R.string.alpha_vmaxfmk), intToString(R.string.alpha_tax), intToString(R.string.alpha_reset), intToString(R.string.alpha_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/alpha.png"));
        carsList.add(new ListModel(intToString(R.string.bandito_name), intToString(R.string.bandito_vmax), intToString(R.string.bandito_vmaxfmk), intToString(R.string.bandito_tax), intToString(R.string.bandito_reset), intToString(R.string.bandito_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bandito.png"));
        carsList.add(new ListModel(intToString(R.string.banshee_name), intToString(R.string.banshee_vmax), intToString(R.string.banshee_vmaxfmk), intToString(R.string.banshee_tax), intToString(R.string.banshee_reset), intToString(R.string.banshee_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/banshee.png"));
        carsList.add(new ListModel(intToString(R.string.bf_name), intToString(R.string.bf_vmax), intToString(R.string.bf_vmaxfmk), intToString(R.string.bf_tax), intToString(R.string.bf_reset), intToString(R.string.bf_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bf.png"));
        carsList.add(new ListModel(intToString(R.string.bf400_name), intToString(R.string.bf400_vmax), intToString(R.string.bf400_vmaxfmk), intToString(R.string.bf400_tax), intToString(R.string.bf400_reset), intToString(R.string.bf400_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bf400.png"));
        carsList.add(new ListModel(intToString(R.string.blade_name), intToString(R.string.blade_vmax), intToString(R.string.blade_vmaxfmk), intToString(R.string.blade_tax), intToString(R.string.blade_reset), intToString(R.string.blade_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/blade.png"));
        carsList.add(new ListModel(intToString(R.string.blista_name), intToString(R.string.blista_vmax), intToString(R.string.blista_vmaxfmk), intToString(R.string.blista_tax), intToString(R.string.blista_reset), intToString(R.string.blista_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/blista.png"));
        carsList.add(new ListModel(intToString(R.string.bobcat_name), intToString(R.string.bobcat_vmax), intToString(R.string.bobcat_vmaxfmk), intToString(R.string.bobcat_tax), intToString(R.string.bobcat_reset), intToString(R.string.bobcat_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bobcat.png"));
        carsList.add(new ListModel(intToString(R.string.bravura_name), intToString(R.string.bravura_vmax), intToString(R.string.bravura_vmaxfmk), intToString(R.string.bravura_tax), intToString(R.string.bravura_reset), intToString(R.string.bravura_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bravura.png"));
        carsList.add(new ListModel(intToString(R.string.broadway_name), intToString(R.string.broadway_vmax), intToString(R.string.broadway_vmaxfmk), intToString(R.string.broadway_tax), intToString(R.string.broadway_reset), intToString(R.string.broadway_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/broadway.png"));
        carsList.add(new ListModel(intToString(R.string.bucaner_name), intToString(R.string.bucaner_vmax), intToString(R.string.bucaner_vmaxfmk), intToString(R.string.bucaner_tax), intToString(R.string.bucaner_reset), intToString(R.string.bucaner_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bucaner.png"));
        carsList.add(new ListModel(intToString(R.string.buffalo_name), intToString(R.string.buffalo_vmax), intToString(R.string.buffalo_vmaxfmk), intToString(R.string.buffalo_tax), intToString(R.string.buffalo_reset), intToString(R.string.buffalo_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/buffalo.png"));
        carsList.add(new ListModel(intToString(R.string.bullet_name), intToString(R.string.bullet_vmax), intToString(R.string.bullet_vmaxfmk), intToString(R.string.bullet_tax), intToString(R.string.bullet_reset), intToString(R.string.bullet_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/bullet.png"));
        carsList.add(new ListModel(intToString(R.string.burrito_name), intToString(R.string.burrito_vmax), intToString(R.string.burrito_vmaxfmk), intToString(R.string.burrito_tax), intToString(R.string.burrito_reset), intToString(R.string.burrito_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/burrito.png"));
        carsList.add(new ListModel(intToString(R.string.cadrona_name), intToString(R.string.cadrona_vmax), intToString(R.string.cadrona_vmaxfmk), intToString(R.string.cadrona_tax), intToString(R.string.cadrona_reset), intToString(R.string.cadrona_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/cadrona.png"));
        carsList.add(new ListModel(intToString(R.string.camper_name), intToString(R.string.camper_vmax), intToString(R.string.camper_vmaxfmk), intToString(R.string.camper_tax), intToString(R.string.camper_reset), intToString(R.string.camper_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/camper.png"));
        carsList.add(new ListModel(intToString(R.string.cheetah_name), intToString(R.string.cheetah_vmax), intToString(R.string.cheetah_vmaxfmk), intToString(R.string.cheetah_tax), intToString(R.string.cheetah_reset), intToString(R.string.cheetah_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/cheetah.png"));
        carsList.add(new ListModel(intToString(R.string.clover_name), intToString(R.string.clover_vmax), intToString(R.string.clover_vmaxfmk), intToString(R.string.clover_tax), intToString(R.string.clover_reset), intToString(R.string.clover_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/clover.png"));
        carsList.add(new ListModel(intToString(R.string.club_name), intToString(R.string.club_vmax), intToString(R.string.club_vmaxfmk), intToString(R.string.club_tax), intToString(R.string.club_reset), intToString(R.string.clover_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/club.png"));
        carsList.add(new ListModel(intToString(R.string.comet_name), intToString(R.string.comet_vmax), intToString(R.string.comet_vmaxfmk), intToString(R.string.comet_tax), intToString(R.string.comet_reset), intToString(R.string.comet_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/comet.png"));
        carsList.add(new ListModel(intToString(R.string.comet_2_name), intToString(R.string.comet_2_vmax), intToString(R.string.comet_2_vmaxfmk), intToString(R.string.comet_2_tax), intToString(R.string.comet_2_reset), intToString(R.string.comet_2_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/comet2.png"));
        carsList.add(new ListModel(intToString(R.string.elegant_name), intToString(R.string.elegant_vmax), intToString(R.string.elegant_vmaxfmk), intToString(R.string.elegant_tax), intToString(R.string.elegant_reset), intToString(R.string.elegant_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/elegant.png"));
        carsList.add(new ListModel(intToString(R.string.elegy_name), intToString(R.string.elegy_vmax), intToString(R.string.elegy_vmaxfmk), intToString(R.string.elegy_tax), intToString(R.string.elegy_reset), intToString(R.string.elegy_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/elegy.png"));
        carsList.add(new ListModel(intToString(R.string.emperor_name), intToString(R.string.emperor_vmax), intToString(R.string.emperor_vmaxfmk), intToString(R.string.emperor_tax), intToString(R.string.emperor_reset), intToString(R.string.emperor_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/emperor.png"));
        carsList.add(new ListModel(intToString(R.string.esperanto_name), intToString(R.string.esperanto_vmax), intToString(R.string.esperanto_vmaxfmk), intToString(R.string.esperanto_tax), intToString(R.string.esperanto_reset), intToString(R.string.esperanto_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/esperanto.png"));
        carsList.add(new ListModel(intToString(R.string.euros_name), intToString(R.string.euros_vmax), intToString(R.string.euros_vmaxfmk), intToString(R.string.euros_tax), intToString(R.string.euros_reset), intToString(R.string.euros_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/euros.png"));
        carsList.add(new ListModel(intToString(R.string.faggio_name), intToString(R.string.faggio_vmax), intToString(R.string.faggio_vmaxfmk), intToString(R.string.faggio_tax), intToString(R.string.faggio_reset), intToString(R.string.faggio_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/faggio.png"));
        carsList.add(new ListModel(intToString(R.string.fcr900_name), intToString(R.string.fcr900_vmax), intToString(R.string.fcr900_vmaxfmk), intToString(R.string.fcr900_tax), intToString(R.string.fcr900_reset), intToString(R.string.fcr900_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/fcr900.png"));
        carsList.add(new ListModel(intToString(R.string.feltzer_name), intToString(R.string.feltzer_vmax), intToString(R.string.feltzer_vmaxfmk), intToString(R.string.feltzer_tax), intToString(R.string.feltzer_reset), intToString(R.string.feltzer_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/feltzer.png"));
        carsList.add(new ListModel(intToString(R.string.flash_name), intToString(R.string.flash_vmax), intToString(R.string.flash_vmaxfmk), intToString(R.string.flash_tax), intToString(R.string.flash_reset), intToString(R.string.flash_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/flash.png"));
        carsList.add(new ListModel(intToString(R.string.fortune_name), intToString(R.string.fortune_vmax), intToString(R.string.fortune_vmaxfmk), intToString(R.string.fortune_tax), intToString(R.string.fortune_reset), intToString(R.string.fortune_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/fortune.png"));
        carsList.add(new ListModel(intToString(R.string.freeway_name), intToString(R.string.freeway_vmax), intToString(R.string.freeway_vmaxfmk), intToString(R.string.freeway_tax), intToString(R.string.freeway_reset), intToString(R.string.freeway_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/freeway.png"));
        carsList.add(new ListModel(intToString(R.string.glendale_name), intToString(R.string.glendale_vmax), intToString(R.string.glendale_vmaxfmk), intToString(R.string.glendale_tax), intToString(R.string.glendale_reset), intToString(R.string.glendale_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/glendale.png"));
        carsList.add(new ListModel(intToString(R.string.greenwood_name), intToString(R.string.greenwood_vmax), intToString(R.string.greenwood_vmaxfmk), intToString(R.string.greenwood_tax), intToString(R.string.greenwood_reset), intToString(R.string.greenwood_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/greenwood.png"));
        carsList.add(new ListModel(intToString(R.string.hermes_name), intToString(R.string.hermes_vmax), intToString(R.string.hermes_vmaxfmk), intToString(R.string.hermes_tax), intToString(R.string.hermes_reset), intToString(R.string.hermes_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/hermes.png"));
        carsList.add(new ListModel(intToString(R.string.hotknife_name), intToString(R.string.hotknife_vmax), intToString(R.string.hotknife_vmaxfmk), intToString(R.string.hotknife_tax), intToString(R.string.hotknife_reset), intToString(R.string.hotknife_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/hotknife.png"));
        carsList.add(new ListModel(intToString(R.string.huntley_name), intToString(R.string.huntley_vmax), intToString(R.string.huntley_vmaxfmk), intToString(R.string.huntley_tax), intToString(R.string.huntley_reset), intToString(R.string.huntley_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/huntley.png"));
        carsList.add(new ListModel(intToString(R.string.hustler_name), intToString(R.string.hustler_vmax), intToString(R.string.hustler_vmaxfmk), intToString(R.string.hustler_tax), intToString(R.string.hustler_reset), intToString(R.string.hustler_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/hustler.png"));
        carsList.add(new ListModel(intToString(R.string.infernus_name), intToString(R.string.infernus_vmax), intToString(R.string.infernus_vmaxfmk), intToString(R.string.infernus_tax), intToString(R.string.infernus_reset), intToString(R.string.infernus_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/infernus.png"));
        carsList.add(new ListModel(intToString(R.string.intruder_name), intToString(R.string.intruder_vmax), intToString(R.string.intruder_vmaxfmk), intToString(R.string.intruder_tax), intToString(R.string.intruder_reset), intToString(R.string.intruder_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/intruder.png"));
        carsList.add(new ListModel(intToString(R.string.jester_name), intToString(R.string.jester_vmax), intToString(R.string.jester_vmaxfmk), intToString(R.string.jester_tax), intToString(R.string.jester_reset), intToString(R.string.jester_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/jester.png"));
        carsList.add(new ListModel(intToString(R.string.journey_name), intToString(R.string.journey_vmax), intToString(R.string.journey_vmaxfmk), intToString(R.string.journey_tax), intToString(R.string.journey_reset), intToString(R.string.journey_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/journey.png"));
        carsList.add(new ListModel(intToString(R.string.landstalker_name), intToString(R.string.landstalker_vmax), intToString(R.string.landstalker_vmaxfmk), intToString(R.string.landstalker_tax), intToString(R.string.landstalker_reset), intToString(R.string.landstalker_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/landstalker.png"));
        carsList.add(new ListModel(intToString(R.string.majestic_name), intToString(R.string.majestic_vmax), intToString(R.string.majestic_vmaxfmk), intToString(R.string.majestic_tax), intToString(R.string.majestic_reset), intToString(R.string.majestic_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/majestic.png"));
        carsList.add(new ListModel(intToString(R.string.manana_name), intToString(R.string.manana_vmax), intToString(R.string.manana_vmaxfmk), intToString(R.string.manana_tax), intToString(R.string.manana_reset), intToString(R.string.manana_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/manana.png"));
        carsList.add(new ListModel(intToString(R.string.merit_name), intToString(R.string.merit_vmax), intToString(R.string.merit_vmaxfmk), intToString(R.string.merit_tax), intToString(R.string.merit_reset), intToString(R.string.merit_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/merit.png"));
        carsList.add(new ListModel(intToString(R.string.mesa_name), intToString(R.string.mesa_vmax), intToString(R.string.mesa_vmaxfmk), intToString(R.string.mesa_tax), intToString(R.string.mesa_reset), intToString(R.string.mesa_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/mesa.png"));
        carsList.add(new ListModel(intToString(R.string.moonbeam_name), intToString(R.string.moonbeam_vmax), intToString(R.string.moonbeam_vmaxfmk), intToString(R.string.moonbeam_tax), intToString(R.string.moonbeam_reset), intToString(R.string.moonbeam_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/moonbeam.png"));
        carsList.add(new ListModel(intToString(R.string.nebula_name), intToString(R.string.nebula_vmax), intToString(R.string.nebula_vmaxfmk), intToString(R.string.nebula_tax), intToString(R.string.nebula_reset), intToString(R.string.nebula_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/nebula.png"));
        carsList.add(new ListModel(intToString(R.string.nrg500_name), intToString(R.string.nrg500_vmax), intToString(R.string.nrg500_vmaxfmk), intToString(R.string.nrg500_tax), intToString(R.string.nrg500_reset), intToString(R.string.nrg500_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/nrg500.png"));
        carsList.add(new ListModel(intToString(R.string.oceanic_name), intToString(R.string.oceanic_vmax), intToString(R.string.oceanic_vmaxfmk), intToString(R.string.oceanic_tax), intToString(R.string.oceanic_reset), intToString(R.string.oceanic_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/oceanic.png"));
        carsList.add(new ListModel(intToString(R.string.patriot_name), intToString(R.string.patriot_vmax), intToString(R.string.patriot_vmaxfmk), intToString(R.string.patriot_tax), intToString(R.string.patriot_reset), intToString(R.string.patriot_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/patriot.png"));
        carsList.add(new ListModel(intToString(R.string.pcj600_name), intToString(R.string.pcj600_vmax), intToString(R.string.pcj600_vmaxfmk), intToString(R.string.pcj600_tax), intToString(R.string.pcj600_reset), intToString(R.string.pcj600_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/pcj600.png"));
        carsList.add(new ListModel(intToString(R.string.perennial_name), intToString(R.string.perennial_vmax), intToString(R.string.perennial_vmaxfmk), intToString(R.string.perennial_tax), intToString(R.string.perennial_reset), intToString(R.string.perennial_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/perennial.png"));
        carsList.add(new ListModel(intToString(R.string.phoenix_name), intToString(R.string.phoenix_vmax), intToString(R.string.phoenix_vmaxfmk), intToString(R.string.phoenix_tax), intToString(R.string.phoenix_reset), intToString(R.string.phoenix_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/phoenix.png"));
        carsList.add(new ListModel(intToString(R.string.picador_name), intToString(R.string.picador_vmax), intToString(R.string.picador_vmaxfmk), intToString(R.string.picador_tax), intToString(R.string.picador_reset), intToString(R.string.picador_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/picador.png"));
        carsList.add(new ListModel(intToString(R.string.pony_name), intToString(R.string.pony_vmax), intToString(R.string.pony_vmaxfmk), intToString(R.string.pony_tax), intToString(R.string.pony_reset), intToString(R.string.pony_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/pony.png"));
        carsList.add(new ListModel(intToString(R.string.premier_name), intToString(R.string.premier_vmax), intToString(R.string.premier_vmaxfmk), intToString(R.string.premier_tax), intToString(R.string.premier_reset), intToString(R.string.premier_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/premier.png"));
        carsList.add(new ListModel(intToString(R.string.previon_name), intToString(R.string.previon_vmax), intToString(R.string.previon_vmaxfmk), intToString(R.string.previon_tax), intToString(R.string.previon_reset), intToString(R.string.previon_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/previon.png"));
        carsList.add(new ListModel(intToString(R.string.primo_name), intToString(R.string.primo_vmax), intToString(R.string.primo_vmaxfmk), intToString(R.string.primo_tax), intToString(R.string.primo_reset), intToString(R.string.primo_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/primo.png"));
        carsList.add(new ListModel(intToString(R.string.quad_name), intToString(R.string.quad_vmax), intToString(R.string.quad_vmaxfmk), intToString(R.string.quad_tax), intToString(R.string.quad_reset), intToString(R.string.quad_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/quad.png"));
        carsList.add(new ListModel(intToString(R.string.rancher_name), intToString(R.string.rancher_vmax), intToString(R.string.rancher_vmaxfmk), intToString(R.string.rancher_tax), intToString(R.string.rancher_reset), intToString(R.string.rancher_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/rancher.png"));
        carsList.add(new ListModel(intToString(R.string.regina_name), intToString(R.string.regina_vmax), intToString(R.string.regina_vmaxfmk), intToString(R.string.regina_tax), intToString(R.string.regina_reset), intToString(R.string.regina_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/regina.png"));
        carsList.add(new ListModel(intToString(R.string.remington_name), intToString(R.string.remington_vmax), intToString(R.string.remington_vmaxfmk), intToString(R.string.remington_tax), intToString(R.string.remington_reset), intToString(R.string.remington_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/remington.png"));
        carsList.add(new ListModel(intToString(R.string.sabre_name), intToString(R.string.sabre_vmax), intToString(R.string.sabre_vmaxfmk), intToString(R.string.sabre_tax), intToString(R.string.sabre_reset), intToString(R.string.sabre_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sabre.png"));
        carsList.add(new ListModel(intToString(R.string.sadler_name), intToString(R.string.sadler_vmax), intToString(R.string.sadler_vmaxfmk), intToString(R.string.sadler_tax), intToString(R.string.sadler_reset), intToString(R.string.sadler_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sadler.png"));
        carsList.add(new ListModel(intToString(R.string.sanchez_name), intToString(R.string.sanchez_vmax), intToString(R.string.sanchez_vmaxfmk), intToString(R.string.sanchez_tax), intToString(R.string.sanchez_reset), intToString(R.string.sanchez_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sanchez.png"));
        carsList.add(new ListModel(intToString(R.string.sandking_name), intToString(R.string.sandking_vmax), intToString(R.string.sandking_vmaxfmk), intToString(R.string.sandking_tax), intToString(R.string.sandking_reset), intToString(R.string.sandking_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sandking.png"));
        carsList.add(new ListModel(intToString(R.string.savanna_name), intToString(R.string.savanna_vmax), intToString(R.string.savanna_vmaxfmk), intToString(R.string.savanna_tax), intToString(R.string.savanna_reset), intToString(R.string.savanna_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/savanna.png"));
        carsList.add(new ListModel(intToString(R.string.sentinelc_name), intToString(R.string.sentinelc_vmax), intToString(R.string.sentinelc_vmaxfmk), intToString(R.string.sentinelc_tax), intToString(R.string.sentinelc_reset), intToString(R.string.sentinelc_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sentinelclassic.png"));
        carsList.add(new ListModel(intToString(R.string.sentinelk_name), intToString(R.string.sentinelk_vmax), intToString(R.string.sentinelk_vmaxfmk), intToString(R.string.sentinelk_tax), intToString(R.string.sentinelk_reset), intToString(R.string.sentinelk_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sentinelcombi.png"));
        carsList.add(new ListModel(intToString(R.string.slamvan_name), intToString(R.string.slamvan_vmax), intToString(R.string.slamvan_vmaxfmk), intToString(R.string.slamvan_tax), intToString(R.string.slamvan_reset), intToString(R.string.slamvan_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/slamvan.png"));
        carsList.add(new ListModel(intToString(R.string.solair_name), intToString(R.string.solair_vmax), intToString(R.string.solair_vmaxfmk), intToString(R.string.solair_tax), intToString(R.string.solair_reset), intToString(R.string.solair_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/solair.png"));
        carsList.add(new ListModel(intToString(R.string.stafford_name), intToString(R.string.stafford_vmax), intToString(R.string.stafford_vmaxfmk), intToString(R.string.stafford_tax), intToString(R.string.stafford_reset), intToString(R.string.stafford_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/stafford.png"));
        carsList.add(new ListModel(intToString(R.string.stallion_name), intToString(R.string.stallion_vmax), intToString(R.string.stallion_vmaxfmk), intToString(R.string.stallion_tax), intToString(R.string.stallion_reset), intToString(R.string.stallion_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/stallion.png"));
        carsList.add(new ListModel(intToString(R.string.stratum_name), intToString(R.string.stratum_vmax), intToString(R.string.stratum_vmaxfmk), intToString(R.string.stratum_tax), intToString(R.string.stratum_reset), intToString(R.string.stratum_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/stratum.png"));
        carsList.add(new ListModel(intToString(R.string.stretch_name), intToString(R.string.stretch_vmax), intToString(R.string.stretch_vmaxfmk), intToString(R.string.stretch_tax), intToString(R.string.stretch_reset), intToString(R.string.stretch_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/stretch.png"));
        carsList.add(new ListModel(intToString(R.string.sultan_name), intToString(R.string.sultan_vmax), intToString(R.string.sultan_vmaxfmk), intToString(R.string.sultan_tax), intToString(R.string.sultan_reset), intToString(R.string.sultan_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sultan.png"));
        carsList.add(new ListModel(intToString(R.string.sunrise_name), intToString(R.string.sunrise_vmax), intToString(R.string.sunrise_vmaxfmk), intToString(R.string.sunrise_tax), intToString(R.string.sunrise_reset), intToString(R.string.sunrise_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/sunrise.png"));
        carsList.add(new ListModel(intToString(R.string.supergt_name), intToString(R.string.supergt_vmax), intToString(R.string.supergt_vmaxfmk), intToString(R.string.supergt_tax), intToString(R.string.supergt_reset), intToString(R.string.supergt_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/supergt.png"));
        carsList.add(new ListModel(intToString(R.string.tahoma_name), intToString(R.string.tahoma_vmax), intToString(R.string.tahoma_vmaxfmk), intToString(R.string.tahoma_tax), intToString(R.string.tahoma_reset), intToString(R.string.tahoma_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tahoma.png"));
        carsList.add(new ListModel(intToString(R.string.tampa_name), intToString(R.string.tampa_vmax), intToString(R.string.tampa_vmaxfmk), intToString(R.string.tampa_tax), intToString(R.string.tampa_reset), intToString(R.string.tampa_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tampa.png"));
        carsList.add(new ListModel(intToString(R.string.tornado_name), intToString(R.string.tornado_vmax), intToString(R.string.tornado_vmaxfmk), intToString(R.string.tornado_tax), intToString(R.string.tornado_reset), intToString(R.string.tornado_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tornado.png"));
        carsList.add(new ListModel(intToString(R.string.turismo_name), intToString(R.string.turismo_vmax), intToString(R.string.turismo_vmaxfmk), intToString(R.string.turismo_tax), intToString(R.string.turismo_reset), intToString(R.string.turismo_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/turismo.png"));
        carsList.add(new ListModel(intToString(R.string.uranus_name), intToString(R.string.uranus_vmax), intToString(R.string.uranus_vmaxfmk), intToString(R.string.uranus_tax), intToString(R.string.uranus_reset), intToString(R.string.uranus_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/uranus.png"));
        carsList.add(new ListModel(intToString(R.string.vincent_name), intToString(R.string.vincent_vmax), intToString(R.string.vincent_vmaxfmk), intToString(R.string.vincent_tax), intToString(R.string.vincent_reset), intToString(R.string.vincent_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/vincent.png"));
        carsList.add(new ListModel(intToString(R.string.virgo_name), intToString(R.string.virgo_vmax), intToString(R.string.virgo_vmaxfmk), intToString(R.string.virgo_tax), intToString(R.string.virgo_reset), intToString(R.string.virgo_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/virgo.png"));
        carsList.add(new ListModel(intToString(R.string.voodoo_name), intToString(R.string.voodoo_vmax), intToString(R.string.voodoo_vmaxfmk), intToString(R.string.voodoo_tax), intToString(R.string.voodoo_reset), intToString(R.string.voodoo_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/voodoo.png"));
        carsList.add(new ListModel(intToString(R.string.walton_name), intToString(R.string.walton_vmax), intToString(R.string.walton_vmaxfmk), intToString(R.string.walton_tax), intToString(R.string.walton_reset), intToString(R.string.walton_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/walton.png"));
        carsList.add(new ListModel(intToString(R.string.washington_name), intToString(R.string.washington_vmax), intToString(R.string.washington_vmaxfmk), intToString(R.string.washingtona_tax), intToString(R.string.washington_reset), intToString(R.string.washington_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/washington.png"));
        carsList.add(new ListModel(intToString(R.string.wayfarer_name), intToString(R.string.wayfarer_vmax), intToString(R.string.wayfarer_vmaxfmk), intToString(R.string.wayfarer_tax), intToString(R.string.wayfarer_reset), intToString(R.string.wayfarer_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wayfarer.png"));
        carsList.add(new ListModel(intToString(R.string.willard_name), intToString(R.string.willard_vmax), intToString(R.string.willard_vmaxfmk), intToString(R.string.willard_tax), intToString(R.string.willard_reset), intToString(R.string.willard_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/willard.png"));
        carsList.add(new ListModel(intToString(R.string.windsor_name), intToString(R.string.windsor_vmax), intToString(R.string.windsor_vmaxfmk), intToString(R.string.windsor_tax), intToString(R.string.windsor_reset), intToString(R.string.windsor_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/windsor.png"));
        carsList.add(new ListModel(intToString(R.string.yosemite_name), intToString(R.string.yosemite_vmax), intToString(R.string.yosemite_vmaxfmk), intToString(R.string.yosemite_tax), intToString(R.string.yosemite_reset), intToString(R.string.yosemite_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/yosemite.png"));
        carsList.add(new ListModel(intToString(R.string.zr350_name), intToString(R.string.zr350_vmax), intToString(R.string.zr350_vmaxfmk), intToString(R.string.zr350_tax), intToString(R.string.zr350_reset), intToString(R.string.zr350_cena), "https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/zr350.png"));
        CarsAdapter adapter = new CarsAdapter(this,this, carsList);
        recyclerView.setAdapter(adapter);
    }

    public String intToString(int Res) {
        return getResources().getString(Res);
    }
}
