package com.feluu.pylife;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.View;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.TextView;

import com.feluu.pylife.adapters.WheelsAdapter;
import com.feluu.pylife.models.ListModel;
import com.feluu.pylife.utils.SharedPref;

import java.util.ArrayList;
import java.util.List;

public class VisualActivity extends AppCompatActivity {

    public RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SharedPref sharedPref = new SharedPref(this);
        if (sharedPref.loadNightModeState()) {
            setTheme(R.style.AppThemeDark);
        } else {
            setTheme(R.style.AppTheme);
        }
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list);

        ImageView leaveActivity;
        ImageView bgMain;
        TextView activityTitle;

        recyclerView = findViewById(R.id.recyclerView);
        leaveActivity = findViewById(R.id.exitActivity);
        bgMain = findViewById(R.id.bgmain);
        activityTitle = findViewById(R.id.top_title);

        activityTitle.setText("Tuning wizualny - " + getIntent().getStringExtra("carName"));
        leaveActivity.setOnClickListener((View v) -> finish());

        if (sharedPref.loadNightModeState()) {
            getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            getWindow().setStatusBarColor(getResources().getColor(R.color.statusColor));
            bgMain.setImageResource(R.drawable.bg_dark);
        }

        setVisu();
    }

    private void setVisu() {
        String car = getIntent().getStringExtra("carName");
        if (car != null) {
            recyclerView.setHasFixedSize(true);
            recyclerView.setLayoutManager(new LinearLayoutManager(this));
            List<ListModel> models;
            models = new ArrayList<>();
            if (car.equalsIgnoreCase("elegy")) {
                models.add(new ListModel(intToString(R.string.elegy_xflow_zderzak_przod_nazwa), intToString(R.string.elegy_xflow_zderzak_przod_cena), intToString(R.string.elegy_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_alien_zderzak_przod_nazwa), intToString(R.string.elegy_alien_zderzak_przod_cena), intToString(R.string.elegy_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_xflow_zderzak_tyl_nazwa), intToString(R.string.elegy_xflow_zderzak_tyl_cena), intToString(R.string.elegy_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_alien_zderzak_tyl_nazwa), intToString(R.string.elegy_alien_zderzak_tyl_cena), intToString(R.string.elegy_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_xflow_progi_nazwa), intToString(R.string.elegy_xflow_progi_cena), intToString(R.string.elegy_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_alien_progi_nazwa), intToString(R.string.elegy_alien_progi_cena), intToString(R.string.elegy_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_xflow_wloty_dach_nazwa), intToString(R.string.elegy_xflow_wloty_dach_cena), intToString(R.string.elegy_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_alien_wloty_dach_nazwa), intToString(R.string.elegy_alien_wloty_dach_cena), intToString(R.string.elegy_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_xflow_wydech_nazwa), intToString(R.string.elegy_xflow_wydech_cena), intToString(R.string.elegy_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_elegy.png"));
                models.add(new ListModel(intToString(R.string.elegy_alien_wydech_nazwa), intToString(R.string.elegy_alien_wydech_cena), intToString(R.string.elegy_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_elegy.png"));
            }
            if (car.equalsIgnoreCase("jester")) {
                models.add(new ListModel(intToString(R.string.jester_xflow_zderzak_przod_nazwa), intToString(R.string.jester_xflow_zderzak_przod_cena), intToString(R.string.jester_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_alien_zderzak_przod_nazwa), intToString(R.string.jester_alien_zderzak_przod_cena), intToString(R.string.jester_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_xflow_zderzak_tyl_nazwa), intToString(R.string.jester_xflow_zderzak_tyl_cena), intToString(R.string.jester_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_alien_zderzak_tyl_nazwa), intToString(R.string.jester_alien_zderzak_tyl_cena), intToString(R.string.jester_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_xflow_progi_nazwa), intToString(R.string.jester_xflow_progi_cena), intToString(R.string.jester_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_alien_progi_nazwa), intToString(R.string.jester_alien_progi_cena), intToString(R.string.jester_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_xflow_wloty_dach_nazwa), intToString(R.string.jester_xflow_wloty_dach_cena), intToString(R.string.jester_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_alien_wloty_dach_nazwa), intToString(R.string.jester_alien_wloty_dach_cena), intToString(R.string.jester_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_xflow_wydech_nazwa), intToString(R.string.jester_xflow_wydech_cena), intToString(R.string.jester_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_jester.png"));
                models.add(new ListModel(intToString(R.string.jester_alien_wydech_nazwa), intToString(R.string.jester_alien_wydech_cena), intToString(R.string.jester_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_jester.png"));
            }
            if (car.equalsIgnoreCase("sultan")) {
                models.add(new ListModel(intToString(R.string.sultan_xflow_zderzak_przod_nazwa), intToString(R.string.sultan_xflow_zderzak_przod_cena), intToString(R.string.sultan_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_alien_zderzak_przod_nazwa), intToString(R.string.sultan_alien_zderzak_przod_cena), intToString(R.string.sultan_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_xflow_zderzak_tyl_nazwa), intToString(R.string.sultan_xflow_zderzak_tyl_cena), intToString(R.string.sultan_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_alien_zderzak_tyl_nazwa), intToString(R.string.sultan_alien_zderzak_tyl_cena), intToString(R.string.sultan_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_xflow_progi_nazwa), intToString(R.string.sultan_xflow_progi_cena), intToString(R.string.sultan_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_alien_progi_nazwa), intToString(R.string.sultan_alien_progi_cena), intToString(R.string.sultan_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_xflow_wloty_dach_nazwa), intToString(R.string.sultan_xflow_wloty_dach_cena), intToString(R.string.sultan_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_alien_wloty_dach_nazwa), intToString(R.string.sultan_alien_wloty_dach_cena), intToString(R.string.sultan_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_xflow_wydech_nazwa), intToString(R.string.sultan_xflow_wydech_cena), intToString(R.string.sultan_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_sultan.png"));
                models.add(new ListModel(intToString(R.string.sultan_alien_wydech_nazwa), intToString(R.string.sultan_alien_wydech_cena), intToString(R.string.sultan_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_sultan.png"));
            }
            if (car.equalsIgnoreCase("uranus")) {
                models.add(new ListModel(intToString(R.string.uranus_xflow_zderzak_przod_nazwa), intToString(R.string.uranus_xflow_zderzak_przod_cena), intToString(R.string.uranus_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_alien_zderzak_przod_nazwa), intToString(R.string.uranus_alien_zderzak_przod_cena), intToString(R.string.uranus_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_xflow_zderzak_tyl_nazwa), intToString(R.string.uranus_xflow_zderzak_tyl_cena), intToString(R.string.uranus_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_alien_zderzak_tyl_nazwa), intToString(R.string.uranus_alien_zderzak_tyl_cena), intToString(R.string.uranus_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_xflow_progi_nazwa), intToString(R.string.uranus_xflow_progi_cena), intToString(R.string.uranus_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_alien_progi_nazwa), intToString(R.string.uranus_alien_progi_cena), intToString(R.string.uranus_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_xflow_wloty_dach_nazwa), intToString(R.string.uranus_xflow_wloty_dach_cena), intToString(R.string.uranus_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_alien_wloty_dach_nazwa), intToString(R.string.uranus_alien_wloty_dach_cena), intToString(R.string.uranus_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_xflow_wydech_nazwa), intToString(R.string.uranus_xflow_wydech_cena), intToString(R.string.uranus_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_uranus.png"));
                models.add(new ListModel(intToString(R.string.uranus_alien_wydech_nazwa), intToString(R.string.uranus_alien_wydech_cena), intToString(R.string.uranus_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_uranus.png"));
            }
            if (car.equalsIgnoreCase("stratum")) {
                models.add(new ListModel(intToString(R.string.stratum_xflow_zderzak_przod_nazwa), intToString(R.string.stratum_xflow_zderzak_przod_cena), intToString(R.string.stratum_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_alien_zderzak_przod_nazwa), intToString(R.string.stratum_alien_zderzak_przod_cena), intToString(R.string.stratum_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_xflow_zderzak_tyl_nazwa), intToString(R.string.stratum_xflow_zderzak_tyl_cena), intToString(R.string.stratum_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_alien_zderzak_tyl_nazwa), intToString(R.string.stratum_alien_zderzak_tyl_cena), intToString(R.string.stratum_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_xflow_progi_nazwa), intToString(R.string.stratum_xflow_progi_cena), intToString(R.string.stratum_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_alien_progi_nazwa), intToString(R.string.stratum_alien_progi_cena), intToString(R.string.stratum_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_xflow_wloty_dach_nazwa), intToString(R.string.stratum_xflow_wloty_dach_cena), intToString(R.string.stratum_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_alien_wloty_dach_nazwa), intToString(R.string.stratum_alien_wloty_dach_cena), intToString(R.string.stratum_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_xflow_wydech_nazwa), intToString(R.string.stratum_xflow_wydech_cena), intToString(R.string.stratum_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_stratum.png"));
                models.add(new ListModel(intToString(R.string.stratum_alien_wydech_nazwa), intToString(R.string.stratum_alien_wydech_cena), intToString(R.string.stratum_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_stratum.png"));
            }
            if (car.equalsIgnoreCase("perennial")) {
                models.add(new ListModel(intToString(R.string.perennial_przeciwmgielne_nazwa), intToString(R.string.perennial_przeciwmgielne_cena), intToString(R.string.perennial_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_perennial.png"));
                models.add(new ListModel(intToString(R.string.perennial_progi_nazwa), intToString(R.string.perennial_progi_cena), intToString(R.string.perennial_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_perennial.png"));
                models.add(new ListModel(intToString(R.string.perennial_twincylinder_wydech_nazwa), intToString(R.string.perennial_twincylinder_wydech_cena), intToString(R.string.perennial_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_twincylinder_perennial.png"));
                models.add(new ListModel(intToString(R.string.perennial_medium_wydech_nazwa), intToString(R.string.perennial_medium_wydech_cena), intToString(R.string.perennial_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_medium_perennial.png"));
                models.add(new ListModel(intToString(R.string.perennial_large_wydech_nazwa), intToString(R.string.perennial_large_wydech_cena), intToString(R.string.perennial_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_large_perennial.png"));
            }
            if (car.equalsIgnoreCase("premier")) {
                models.add(new ListModel(intToString(R.string.premier_champ_maska_nazwa), intToString(R.string.premier_champ_maska_cena), intToString(R.string.premier_champ_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_champ_premier.png"));
                models.add(new ListModel(intToString(R.string.premier_fury_maska_nazwa), intToString(R.string.premier_fury_maska_cena), intToString(R.string.premier_fury_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_fury_premier.png"));
                models.add(new ListModel(intToString(R.string.premier_wloty_nazwa), intToString(R.string.premier_wloty_cena), intToString(R.string.premier_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_premier.png"));
                models.add(new ListModel(intToString(R.string.premier_twincylinder_wydech_nazwa), intToString(R.string.premier_twincylinder_wydech_cena), intToString(R.string.premier_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_twincylinder_premier.png"));
                models.add(new ListModel(intToString(R.string.premier_medium_wydech_nazwa), intToString(R.string.premier_medium_wydech_cena), intToString(R.string.premier_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_medium_premier.png"));
            }
            if (car.equalsIgnoreCase("phoenix")) {
                models.add(new ListModel(intToString(R.string.phoenix_oval_wentylacja_nazwa), intToString(R.string.phoenix_oval_wentylacja_cena), intToString(R.string.phoenix_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_square_wentylacja_nazwa), intToString(R.string.phoenix_square_wentylacja_cena), intToString(R.string.phoenix_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_wloty_nazwa), intToString(R.string.phoenix_wloty_cena), intToString(R.string.phoenix_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_progi_nazwa), intToString(R.string.phoenix_progi_cena), intToString(R.string.phoenix_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_upsweptc_wydech_nazwa), intToString(R.string.phoenix_upsweptc_wydech_cena), intToString(R.string.phoenix_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_twincylinder_wydech_nazwa), intToString(R.string.phoenix_twincylinder_wydech_cena), intToString(R.string.phoenix_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_phoenix.png"));
                models.add(new ListModel(intToString(R.string.phoenix_large_wydech_nazwa), intToString(R.string.phoenix_large_wydech_cena), intToString(R.string.phoenix_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_phoenix.png"));
            }
            if (car.equalsIgnoreCase("zr-350")) {
                models.add(new ListModel(intToString(R.string.zr350_wloty_nazwa), intToString(R.string.zr350_wloty_cena), intToString(R.string.zr350_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_zr350.png"));
                models.add(new ListModel(intToString(R.string.zr350_progi_nazwa), intToString(R.string.zr350_progi_cena), intToString(R.string.zr350_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_zr350.png"));
                models.add(new ListModel(intToString(R.string.zr350_upsweptc_wydech_nazwa), intToString(R.string.zr350_upsweptc_wydech_cena), intToString(R.string.zr350_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_zr350.png"));
                models.add(new ListModel(intToString(R.string.zr350_twincylinder_wydech_nazwa), intToString(R.string.zr350_twincylinder_wydech_cena), intToString(R.string.zr350_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_zr350.png"));
                models.add(new ListModel(intToString(R.string.zr350_large_wydech_nazwa), intToString(R.string.zr350_large_wydech_cena), intToString(R.string.zr350_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_zr350.png"));
                models.add(new ListModel(intToString(R.string.zr350_medium_wydech_nazwa), intToString(R.string.zr350_medium_wydech_cena), intToString(R.string.zr350_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_zr350.png"));
            }
            if (car.equalsIgnoreCase("flash")) {
                models.add(new ListModel(intToString(R.string.flash_xflow_zderzak_przod_nazwa), intToString(R.string.flash_xflow_zderzak_przod_cena), intToString(R.string.flash_xflow_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_xflow_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_alien_zderzak_przod_nazwa), intToString(R.string.flash_alien_zderzak_przod_cena), intToString(R.string.flash_alien_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_alien_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_xflow_zderzak_tyl_nazwa), intToString(R.string.flash_xflow_zderzak_tyl_cena), intToString(R.string.flash_xflow_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_xflow_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_alien_zderzak_tyl_nazwa), intToString(R.string.flash_alien_zderzak_tyl_cena), intToString(R.string.flash_alien_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_alien_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_xflow_progi_nazwa), intToString(R.string.flash_xflow_progi_cena), intToString(R.string.flash_xflow_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_xflow_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_alien_progi_nazwa), intToString(R.string.flash_alien_progi_cena), intToString(R.string.flash_alien_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_alien_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_xflow_wloty_dach_nazwa), intToString(R.string.flash_xflow_wloty_dach_cena), intToString(R.string.flash_xflow_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_xflow_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_alien_wloty_dach_nazwa), intToString(R.string.flash_alien_wloty_dach_cena), intToString(R.string.flash_alien_wloty_dach_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_alien_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_xflow_wydech_nazwa), intToString(R.string.flash_xflow_wydech_cena), intToString(R.string.flash_xflow_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_xflow_flash.png"));
                models.add(new ListModel(intToString(R.string.flash_alien_wydech_nazwa), intToString(R.string.flash_alien_wydech_cena), intToString(R.string.flash_alien_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_alien_flash.png"));
            }
            if (car.equalsIgnoreCase("tornado")) {
                models.add(new ListModel(intToString(R.string.tornado_chrome_zderzak_przod_nazwa), intToString(R.string.tornado_chrome_zderzak_przod_cena), intToString(R.string.tornado_chrome_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_chrome_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_slamin_zderzak_przod_nazwa), intToString(R.string.tornado_slamin_zderzak_przod_cena), intToString(R.string.tornado_slamin_zderzak_przod_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_slamin_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_chrome_zderzak_tyl_nazwa), intToString(R.string.tornado_chrome_zderzak_tyl_cena), intToString(R.string.tornado_chrome_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_chrome_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_slamin_zderzak_tyl_nazwa), intToString(R.string.tornado_slamin_zderzak_tyl_cena), intToString(R.string.tornado_slamin_zderzak_tyl_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_slamin_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_chrome_progi_nazwa), intToString(R.string.tornado_chrome_progi_cena), intToString(R.string.tornado_chrome_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_chrome_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_chrome_wydech_nazwa), intToString(R.string.tornado_chrome_wydech_cena), intToString(R.string.tornado_chrome_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_chrome_tornado.png"));
                models.add(new ListModel(intToString(R.string.tornado_slamin_wydech_nazwa), intToString(R.string.tornado_slamin_wydech_cena), intToString(R.string.tornado_slamin_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_slamin_tornado.png"));
            }
            if (car.equalsIgnoreCase("blista")) {
                models.add(new ListModel(intToString(R.string.blista_race_maska_nazwa), intToString(R.string.blista_race_maska_cena), intToString(R.string.blista_race_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_race_blista.png"));
                models.add(new ListModel(intToString(R.string.blista_oval_wentylacja_nazwa), intToString(R.string.blista_oval_wentylacja_cena), intToString(R.string.blista_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_blista.png"));
                models.add(new ListModel(intToString(R.string.blista_wloty_nazwa), intToString(R.string.blista_wloty_cena), intToString(R.string.blista_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_blista.png"));
                models.add(new ListModel(intToString(R.string.blista_progi_nazwa), intToString(R.string.blista_progi_cena), intToString(R.string.blista_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_blista.png"));
                models.add(new ListModel(intToString(R.string.blista_twincylinder_wydech_nazwa), intToString(R.string.blista_twincylinder_wydech_cena), intToString(R.string.blista_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_twincylinder_blista.png"));
                models.add(new ListModel(intToString(R.string.blista_large_wydech_nazwa), intToString(R.string.blista_large_wydech_cena), intToString(R.string.blista_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_large_blista.png"));
            }
            if (car.equalsIgnoreCase("bravura")) {
                models.add(new ListModel(intToString(R.string.bravura_przeciwmgielne_nazwa), intToString(R.string.bravura_przeciwmgielne_cena), intToString(R.string.bravura_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_oval_wentylacja_nazwa), intToString(R.string.bravura_oval_wentylacja_cena), intToString(R.string.bravura_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_square_wentylacja_nazwa), intToString(R.string.bravura_square_wentylacja_cena), intToString(R.string.bravura_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_wloty_nazwa), intToString(R.string.bravura_wloty_cena), intToString(R.string.bravura_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_progi_nazwa), intToString(R.string.bravura_progi_cena), intToString(R.string.bravura_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_twincylinder_wydech_nazwa), intToString(R.string.bravura_twincylinder_wydech_cena), intToString(R.string.bravura_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_bravura.png"));
                models.add(new ListModel(intToString(R.string.bravura_large_wydech_nazwa), intToString(R.string.bravura_large_wydech_cena), intToString(R.string.bravura_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_bravura.png"));
            }
            if (car.equalsIgnoreCase("cadrona")) {
                models.add(new ListModel(intToString(R.string.cadrona_progi_nazwa), intToString(R.string.cadrona_progi_cena), intToString(R.string.cadrona_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_cadrona.png"));
                models.add(new ListModel(intToString(R.string.cadrona_upsweptc_wydech_nazwa), intToString(R.string.cadrona_upsweptc_wydech_cena), intToString(R.string.cadrona_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_cadrona.png"));
                models.add(new ListModel(intToString(R.string.cadrona_large_wydech_nazwa), intToString(R.string.cadrona_large_wydech_cena), intToString(R.string.cadrona_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_cadrona.png"));
                models.add(new ListModel(intToString(R.string.cadrona_medium_wydech_nazwa), intToString(R.string.cadrona_medium_wydech_cena), intToString(R.string.cadrona_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_medium_cadrona.png"));
            }
            if (car.equalsIgnoreCase("clover")) {
                models.add(new ListModel(intToString(R.string.clover_square_wentylacja_nazwa), intToString(R.string.clover_square_wentylacja_cena), intToString(R.string.clover_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_clover.png"));
                models.add(new ListModel(intToString(R.string.clover_upsweptc_wydech_nazwa), intToString(R.string.clover_upsweptc_wydech_cena), intToString(R.string.clover_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_clover.png"));
                models.add(new ListModel(intToString(R.string.clover_twincylinder_wydech_nazwa), intToString(R.string.clover_twincylinder_wydech_cena), intToString(R.string.clover_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_clover.png"));
                models.add(new ListModel(intToString(R.string.clover_large_wydech_nazwa), intToString(R.string.clover_large_wydech_cena), intToString(R.string.clover_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_large_clover.png"));
                models.add(new ListModel(intToString(R.string.clover_medium_wydech_nazwa), intToString(R.string.clover_medium_wydech_cena), intToString(R.string.clover_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydech_medium_clover.png"));
            }
            if (car.equalsIgnoreCase("majestic")) {
                models.add(new ListModel(intToString(R.string.majestic_oval_wentylacja_nazwa), intToString(R.string.majestic_oval_wentylacja_cena), intToString(R.string.majestic_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_majestic.png"));
                models.add(new ListModel(intToString(R.string.majestic_square_wentylacja_nazwa), intToString(R.string.majestic_square_wentylacja_cena), intToString(R.string.majestic_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_majestic.png"));
                models.add(new ListModel(intToString(R.string.majestic_progi_nazwa), intToString(R.string.majestic_progi_cena), intToString(R.string.majestic_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_majestic.png"));
                models.add(new ListModel(intToString(R.string.majestic_upsweptc_wydech_nazwa), intToString(R.string.majestic_upsweptc_wydech_cena), intToString(R.string.majestic_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_majestic.png"));
                models.add(new ListModel(intToString(R.string.majestic_twincylinder_wydech_nazwa), intToString(R.string.majestic_twincylinder_wydech_cena), intToString(R.string.majestic_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_majestic.png"));
                models.add(new ListModel(intToString(R.string.majestic_large_wydech_nazwa), intToString(R.string.majestic_large_wydech_cena), intToString(R.string.majestic_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_majestic.png"));
            }
            if (car.equalsIgnoreCase("manana")) {
                models.add(new ListModel(intToString(R.string.manana_przeciwmgielne_nazwa), intToString(R.string.manana_przeciwmgielne_cena), intToString(R.string.manana_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_manana.png"));
                models.add(new ListModel(intToString(R.string.manana_square_przeciwmgielne_nazwa), intToString(R.string.manana_square_przeciwmgielne_cena), intToString(R.string.manana_square_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_square_manana.png"));
                models.add(new ListModel(intToString(R.string.manana_progi_nazwa), intToString(R.string.manana_progi_cena), intToString(R.string.manana_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_manana.png"));
                models.add(new ListModel(intToString(R.string.manana_twincylinder_wydech_nazwa), intToString(R.string.manana_twincylinder_wydech_cena), intToString(R.string.manana_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_manana.png"));
                models.add(new ListModel(intToString(R.string.manana_large_wydech_nazwa), intToString(R.string.manana_large_wydech_cena), intToString(R.string.manana_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_manana.png"));
            }
            if (car.equalsIgnoreCase("previon")) {
                models.add(new ListModel(intToString(R.string.previon_przeciwmgielne_nazwa), intToString(R.string.previon_przeciwmgielne_cena), intToString(R.string.previon_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_wloty_nazwa), intToString(R.string.previon_wloty_cena), intToString(R.string.previon_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_progi_nazwa), intToString(R.string.previon_progi_cena), intToString(R.string.previon_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_twincylinder_wydech_nazwa), intToString(R.string.previon_twincylinder_wydech_cena), intToString(R.string.previon_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_large_wydech_nazwa), intToString(R.string.previon_large_wydech_cena), intToString(R.string.previon_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_medium_wydech_nazwa), intToString(R.string.previon_medium_wydech_cena), intToString(R.string.previon_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_previon.png"));
                models.add(new ListModel(intToString(R.string.previon_small_wydech_nazwa), intToString(R.string.previon_small_wydech_cena), intToString(R.string.previon_small_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_small_previon.png"));
            }
            if (car.equalsIgnoreCase("stallion")) {
                models.add(new ListModel(intToString(R.string.stallion_przeciwmgielne_nazwa), intToString(R.string.stallion_przeciwmgielne_cena), intToString(R.string.stallion_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_stallion.png"));
                models.add(new ListModel(intToString(R.string.stallion_oval_wentylacja_nazwa), intToString(R.string.stallion_oval_wentylacja_cena), intToString(R.string.stallion_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_stallion.png"));
                models.add(new ListModel(intToString(R.string.stallion_square_wentylacja_nazwa), intToString(R.string.stallion_square_wentylacja_cena), intToString(R.string.stallion_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_stallion.png"));
                models.add(new ListModel(intToString(R.string.stallion_progi_nazwa), intToString(R.string.stallion_progi_cena), intToString(R.string.stallion_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_stallion.png"));
            }
            if (car.equalsIgnoreCase("tampa")) {
                models.add(new ListModel(intToString(R.string.tampa_race_maska_nazwa), intToString(R.string.tampa_race_maska_cena), intToString(R.string.tampa_race_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_race_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_worx_maska_nazwa), intToString(R.string.tampa_worx_maska_cena), intToString(R.string.tampa_worx_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_worx_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_oval_wentylacja_nazwa), intToString(R.string.tampa_oval_wentylacja_cena), intToString(R.string.tampa_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_square_wentylacja_nazwa), intToString(R.string.tampa_square_wentylacja_cena), intToString(R.string.tampa_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_progi_nazwa), intToString(R.string.tampa_progi_cena), intToString(R.string.tampa_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_upsweptc_wydech_nazwa), intToString(R.string.tampa_upsweptc_wydech_cena), intToString(R.string.tampa_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_twincylinder_wydech_nazwa), intToString(R.string.tampa_twincylinder_wydech_cena), intToString(R.string.tampa_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_tampa.png"));
                models.add(new ListModel(intToString(R.string.tampa_large_wydech_nazwa), intToString(R.string.tampa_large_wydech_cena), intToString(R.string.tampa_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_tampa.png"));
            }
            if (car.equalsIgnoreCase("emperor")) {
                models.add(new ListModel(intToString(R.string.emperor_przeciwmgielne_nazwa), intToString(R.string.emperor_przeciwmgielne_cena), intToString(R.string.emperor_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_oval_wentylacja_nazwa), intToString(R.string.emperor_oval_wentylacja_cena), intToString(R.string.emperor_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_square_wentylacja_nazwa), intToString(R.string.emperor_square_wentylacja_cena), intToString(R.string.emperor_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_wloty_nazwa), intToString(R.string.emperor_wloty_cena), intToString(R.string.emperor_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wlot_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_progi_nazwa), intToString(R.string.emperor_progi_cena), intToString(R.string.emperor_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_upsweptc_wydech_nazwa), intToString(R.string.emperor_upsweptc_wydech_cena), intToString(R.string.emperor_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_twincylinder_wydech_nazwa), intToString(R.string.emperor_twincylinder_wydech_cena), intToString(R.string.emperor_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_emperor.png"));
                models.add(new ListModel(intToString(R.string.emperor_large_wydech_nazwa), intToString(R.string.emperor_large_wydech_cena), intToString(R.string.emperor_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_emperor.png"));
            }
            if (car.equalsIgnoreCase("greenwood")) {
                models.add(new ListModel(intToString(R.string.greenwood_champ_maska_nazwa), intToString(R.string.greenwood_champ_maska_cena), intToString(R.string.greenwood_champ_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_champ_greenwood.png"));
                models.add(new ListModel(intToString(R.string.greenwood_fury_maska_nazwa), intToString(R.string.premier_fury_maska_cena), intToString(R.string.premier_fury_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_fury_greenwood.png"));
                models.add(new ListModel(intToString(R.string.greenwood_wloty_nazwa), intToString(R.string.greenwood_wloty_cena), intToString(R.string.greenwood_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_greenwood.png"));
            }
            if (car.equalsIgnoreCase("intruder")) {
                models.add(new ListModel(intToString(R.string.intruder_square_przeciwmgielne_nazwa), intToString(R.string.intruder_square_przeciwmgielne_cena), intToString(R.string.intruder_square_przeciwmgielne_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przeciwmgielne_square_intruder.png"));
                models.add(new ListModel(intToString(R.string.intruder_oval_wentylacja_nazwa), intToString(R.string.intruder_oval_wentylacja_cena), intToString(R.string.intruder_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_intruder.png"));
                models.add(new ListModel(intToString(R.string.intruder_square_wentylacja_nazwa), intToString(R.string.intruder_square_wentylacja_cena), intToString(R.string.intruder_square_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_square_intruder.png"));
                models.add(new ListModel(intToString(R.string.intruder_progi_nazwa), intToString(R.string.intruder_progi_cena), intToString(R.string.intruder_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_intruder.png"));
                models.add(new ListModel(intToString(R.string.intruder_upsweptc_wydech_nazwa), intToString(R.string.intruder_upsweptc_wydech_cena), intToString(R.string.intruder_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_intruder.png"));
                models.add(new ListModel(intToString(R.string.intruder_twincylinder_wydech_nazwa), intToString(R.string.intruder_twincylinder_wydech_cena), intToString(R.string.intruder_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_intruder.png"));
            }
			if (car.equalsIgnoreCase("merit")) { 
		        models.add(new ListModel(intToString(R.string.merit_fury_maska_nazwa), intToString(R.string.merit_fury_maska_cena), intToString(R.string.merit_fury_maska_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/maska_fury_merit.png"));
				models.add(new ListModel(intToString(R.string.merit_wloty_nazwa), intToString(R.string.merit_wloty_cena), intToString(R.string.merit_wloty_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wloty_merit.png"));
				models.add(new ListModel(intToString(R.string.merit_upsweptc_wydech_nazwa), intToString(R.string.merit_upsweptc_wydech_cena), intToString(R.string.merit_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_merit.png"));
                models.add(new ListModel(intToString(R.string.merit_twincylinder_wydech_nazwa), intToString(R.string.merit_twincylinder_wydech_cena), intToString(R.string.merit_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_merit.png"));
                models.add(new ListModel(intToString(R.string.merit_large_wydech_nazwa), intToString(R.string.merit_large_wydech_cena), intToString(R.string.merit_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_merit.png"));
			    models.add(new ListModel(intToString(R.string.merit_medium_wydech_nazwa), intToString(R.string.merit_medium_wydech_cena), intToString(R.string.merit_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_merit.png"));
            }
			if (car.equalsIgnoreCase("nebula")) { 
			    models.add(new ListModel(intToString(R.string.nebula_progi_nazwa), intToString(R.string.nebula_progi_cena), intToString(R.string.nebula_progi_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/progi_nebula.png"));
				models.add(new ListModel(intToString(R.string.nebula_upsweptc_wydech_nazwa), intToString(R.string.nebula_upsweptc_wydech_cena), intToString(R.string.nebula_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_nebula.png"));
                models.add(new ListModel(intToString(R.string.nebula_twincylinder_wydech_nazwa), intToString(R.string.nebula_twincylinder_wydech_cena), intToString(R.string.nebula_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_nebula.png"));
                models.add(new ListModel(intToString(R.string.nebula_large_wydech_nazwa), intToString(R.string.nebula_large_wydech_cena), intToString(R.string.nebula_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_nebula.png"));
			    models.add(new ListModel(intToString(R.string.nebula_medium_wydech_nazwa), intToString(R.string.nebula_medium_wydech_cena), intToString(R.string.nebula_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_nebula.png"));
            }
			if (car.equalsIgnoreCase("primo")) { 
                models.add(new ListModel(intToString(R.string.primo_oval_wentylacja_nazwa), intToString(R.string.primo_oval_wentylacja_cena), intToString(R.string.primo_oval_wentylacja_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wentylacja_oval_primo.png"));
				models.add(new ListModel(intToString(R.string.primo_upsweptc_wydech_nazwa), intToString(R.string.primo_upsweptc_wydech_cena), intToString(R.string.primo_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_primo.png"));
                models.add(new ListModel(intToString(R.string.primo_twincylinder_wydech_nazwa), intToString(R.string.primo_twincylinder_wydech_cena), intToString(R.string.primo_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_primo.png"));
                models.add(new ListModel(intToString(R.string.primo_large_wydech_nazwa), intToString(R.string.primo_large_wydech_cena), intToString(R.string.primo_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_primo.png"));
			    models.add(new ListModel(intToString(R.string.primo_medium_wydech_nazwa), intToString(R.string.primo_medium_wydech_cena), intToString(R.string.primo_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_primo.png"));
            }
			if (car.equalsIgnoreCase("sentinel")) { 
				models.add(new ListModel(intToString(R.string.sentinel_upsweptc_wydech_nazwa), intToString(R.string.sentinel_upsweptc_wydech_cena), intToString(R.string.sentinel_upsweptc_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_upsweptc_sentinel.png"));
                models.add(new ListModel(intToString(R.string.sentinel_twincylinder_wydech_nazwa), intToString(R.string.sentinel_twincylinder_wydech_cena), intToString(R.string.sentinel_twincylinder_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_twincylinder_sentinel.png"));
                models.add(new ListModel(intToString(R.string.sentinel_large_wydech_nazwa), intToString(R.string.sentinel_large_wydech_cena), intToString(R.string.sentinel_large_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_large_sentinel.png"));
			    models.add(new ListModel(intToString(R.string.sentinel_medium_wydech_nazwa), intToString(R.string.sentinel_medium_wydech_cena), intToString(R.string.sentinel_medium_wydech_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_medium_sentinel.png"));
            }	
			if (car.equalsIgnoreCase("remington")) { 
		       models.add(new ListModel(intToString(R.string.remek_przedni_zderzak_chrome_nazwa),intToString(R.string.remek_przedni_zderzak_chrome_cena),intToString(R.string.remek_przedni_zderzak_chrome_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_chrome_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_przedni_zderzak_slamin_nazwa),intToString(R.string.remek_przedni_zderzak_slamin_cena),intToString(R.string.remek_przedni_zderzak_slamin_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/przedni_zderzak_slamin_remek.png"));
	           models.add(new ListModel(intToString(R.string.remek_grillczaszka_nazwa),intToString(R.string.remek_grillczaszka_cena),intToString(R.string.remek_grillczaszka_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/grillczaszka_remek.png"));
	           models.add(new ListModel(intToString(R.string.remek_grillkrata_nazwa),intToString(R.string.remek_grillkrata_cena),intToString(R.string.remek_grillkrata_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/grillkrata_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_oslona_nazwa),intToString(R.string.remek_oslona_cena),intToString(R.string.remek_oslona_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/oslony_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_listwy_nadkola_nazwa),intToString(R.string.remek_listwy_nadkola_cena),intToString(R.string.remek_listwy_nadkola_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/listwy_nadkola_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_plonace_nadkola_nazwa),intToString(R.string.remek_plonace_nadkola_cena),intToString(R.string.remek_plonace_nadkola_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/plonace_nadkola_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_tylni_zderzak_chrome_nazwa),intToString(R.string.remek_tylni_zderzak_chrome_cena),intToString(R.string.remek_tylni_zderzak_chrome_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_chrome_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_tylni_zderzak_slamin_nazwa),intToString(R.string.remek_tylni_zderzak_slamin_cena),intToString(R.string.remek_tylni_zderzak_slamin_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/tylni_zderzak_slamin_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_wydechy_chrome_nazwa),intToString(R.string.remek_wydechy_chrome_cena),intToString(R.string.remek_wydechy_chrome_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_chrome_remek.png"));
		       models.add(new ListModel(intToString(R.string.remek_wydechy_slamin_nazwa),intToString(R.string.remek_wydechy_slamin_cena),intToString(R.string.remek_wydechy_slamin_demont), null, null, null,"https://raw.githubusercontent.com/Msciciel55/Play-Your-Life-Mobile/master/res/drawable/wydechy_slamin_remek.png"));
            }



                WheelsAdapter adapter = new WheelsAdapter(this, models);
            recyclerView.setAdapter(adapter);
        }
        else {
            finish();
        }
    }

    private String intToString(int Res) {
        return getResources().getString(Res);
    }
}